version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER : ${MYSQL_USER}
      MYSQL_PASSWORD : ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    expose:
      - ${MYSQL_PORT}
    volumes:
      - ./docker/volumes/:/var/lib/mysql

  app:
    image: node:18-alpine
    restart: always
    command: sh -c "yarn && yarn db:generate && yarn start:dev"
    working_dir: /app
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${DOCKER_MYSQL_HOST}:${DOCKER_MYSQL_PORT}/${MYSQL_DATABASE}
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - db
    volumes:
      - ./:/app
