name: Deploy Backend
on:
    workflow_dispatch:
    # push:
    #     branches:
    #         - main

jobs:
    build:
        name: Deploy Backend
        runs-on: ubuntu-latest
        steps:
            - name: Connect to server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  port: 22
                  script: |
                      cd /var/www/backend
                      git stash
                      git pull --rebase
                      nest build
                      pm2 delete backend
                      pm2 start dist/main.js --name backend
                      pm2 save
                      pm2 restart backend
                      systemctl restart nginx
